// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
   
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
        
        
//    <nav className="navbar" dir="ltr">
//         <div className="navbar-content ">
//           <div className="navbar-right ">

//           <div className="navbar-links ">
//               <a href="/addasset" className="navbar-link text-md font-bold">
//                 اضافة الأصول
//               </a>
//             </div>


//             <div className="navbar-links">
//               <a href="/assetadminstration" className="navbar-link text-md font-bold">
//                 ادارة الأصول
//               </a>
//             </div>


//             <div className="navbar-links">
//               <a href="/assetform" className="navbar-link text-md font-bold">
// اسناد عهدة
//               </a>
//             </div>
//             <div className="navbar-links">
//               <a href="/CustodyManagement" className="navbar-link text-md font-bold">
// ادارة العهد              
// </a>
//             </div>
//             <div className="navbar-logo">
//               <img
//                 src="/media/logo.png"
//                 alt="Logo"
//                 className="logo"
//               />
//             </div>
//           </div>
//         </div>
//       </nav>
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthGuard from './components/AuthGuard'; // استيراد المكون الجديد

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthGuard>
          {children}
        </AuthGuard>
      </body>
    </html>
  );
}